# See: https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
  name = "github.com/docker/distribution"

# glog -> zap
[[override]]
  revision = "80c6663f0864be2efa0d7a5d7ba05c1a16256e64"
  name = "github.com/golang/glog"
  source = "github.com/prydie/glog"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.1"

[[override]]
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"
  name = "k8s.io/kube-openapi"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "go.uber.org/zap"
    version = "1.9.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~9.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.12.1"

[[constraint]]
 name = "github.com/kubernetes-incubator/external-storage"
 version = "4.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.2"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "2.6.0"

[prune]
  non-go = true

  [[prune.project]]
    name = "github.com/docker/docker"
    go-tests = true
    unused-packages = true
